# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Use a package of configuration called an orb.
orbs:
  win: circleci/windows@1.0.0

jobs:
  build_windows:
    executor: win/vs2019
    steps:
      - add_ssh_keys:
        fingerprints:
          - "0d:c9:07:1e:64:9d:7e:b8:05:e6:3c:eb:8d:9f:44:ea"
      - checkout
      - run:
          name: "Running premake"
          shell: cmd.exe
          working_directory: "./make"
          command: cmd "call premake_vs2019.bat"
      - run:
          name: "Building executable"
          shell: cmd.exe
          working_directory: "./make"
          command: cmd "call build_vs2019.bat"
  unit_test:
    executor: win/vs2019
    steps:
      - checkout

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_windows
      - unit_test:
          requires:
            - build_windows
    
