# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Use a package of configuration called an orb.
orbs:
  win: circleci/windows@1.0.0

jobs:
  build_windows:
    executor: win/vs2019
    steps:
      - run: mkdir -p workspace
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is 
          # taken to be the root directory of the workspace.
          root: workspace
          # Must be relative path from root
          paths:
            - ./
      - checkout
      - run:
          name: "Running premake"
          shell: cmd.exe
          command: call make/premake5_vs2019.bat
      - run:
          name: "Building executable"
          shell: cmd.exe
          command: call make/build_vs2019.bat
  unit_test:
    executor: win/vs2019
    steps:
      - attach_workspace: workspace
      - run:
          name: "Running premake"
          shell: cmd.exe
          command: call make/premake5_vs2017.bat

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_windows
      - unit_test:
          requires:
            - build_windows
    
